# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Maddys Site
tagline:          An Awesome website
url:              http://roachhd.github.io/maddy
paginate:         20
baseurl:          /maddy
author:
  name:           Maddison S
  url:            https://twitter.com/mektball
  email:          katie@roachhd.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/roachhd/maddy
